FROM ubuntu:19.04

RUN apt-get -y update && \
    apt-get -y install software-properties-common wget

RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|apt-key add -

RUN add-apt-repository 'deb http://apt.llvm.org/disco/ llvm-toolchain-disco-10 main'

RUN apt-get install -y libllvm-10-ocaml-dev \
    libllvm10 llvm-10 llvm-10-dev llvm-10-doc llvm-10-examples llvm-10-runtime

RUN apt-get install -y clang-10 clang-tools-10 clang-10-doc libclang-common-10-dev \
    libclang-10-dev libclang1-10 clang-format-10 clangd-10

RUN apt-get -y install clang-format clang-tidy clang-tools clang libc++-dev libc++1 \
    libc++abi-dev libc++abi1 libclang-dev libclang1 liblldb-dev libllvm-ocaml-dev \
    libomp-dev libomp5 lld lldb llvm-dev llvm-runtime llvm python-clang

RUN apt-get -y install wget apt-utils git cmake gdb gettext git libicu-dev \
    libunwind8 llvm make tar wget zip

RUN wget -q https://packages.microsoft.com/config/ubuntu/19.04/packages-microsoft-prod.deb \
    -O packages-microsoft-prod.deb && dpkg -i packages-microsoft-prod.deb

RUN apt-get -y install apt-transport-https
RUN apt-get -y update && apt-get -y install dotnet-sdk-3.1

WORKDIR /app

RUN git clone https://github.com/dotnet/diagnostics.git
RUN git clone https://github.com/dotnet/runtime.git
RUN git clone https://github.com/dotnet/symstore.git
RUN git clone https://github.com/dotnet/dotnet-buildtools-prereqs-docker.git
RUN git clone https://github.com/dotnet/sdk.git
RUN git clone https://github.com/dotnet/roslyn-sdk.git
RUN git clone https://github.com/dotnet/core
RUN git clone https://github.com/dotnet/roslyn-tools
RUN git clone https://github.com/dotnet/corefx
RUN git clone https://github.com/dotnet/source-build
RUN git clone https://github.com/dotnet/symreader-portable
RUN git clone https://github.com/dotnet/symreader
RUN git clone https://github.com/dotnet/sourcelink
RUN git clone https://github.com/dotnet/metadata-tools
RUN git clone https://github.com/dotnet/toolset
RUN git clone https://github.com/dotnet/llvm-project
RUN git clone https://github.com/dotnet/vscode-dotnet-runtime
RUN git clone https://github.com/dotnet/buildtools
RUN git clone https://github.com/dotnet/ILMerge
RUN git clone https://github.com/dotnet/corefx-tools
RUN git clone https://github.com/dotnet/standard
RUN git clone https://github.com/dotnet/coreclr
RUN git clone https://github.com/dotnet/roslyn


RUN ./dotnet/dotnet-buildtools-prereqs-docker/build.sh --configuration debug
RUN ./diagnostics/build.sh --configuration debug
RUN ./symstore/build.sh --configuration debug

#RUN ./runtime/build.sh --configuration debug
#RUN dotnet tool install -g dotnet-symbol

ENV PATH="/root/.dotnet/tools:/usr/lib/llvm-10/bin:${PATH}"
