FROM ubuntu:18.04

RUN apt-get update -y && apt-get upgrade -y

RUN apt-get -y update && \
    apt-get -y install wget apt-utils llvm-8 lldb-8

RUN wget -q https://packages.microsoft.com/config/ubuntu/19.04/packages-microsoft-prod.deb \
    -O packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb

RUN apt-get -y update && \
    apt-get -y install apt-transport-https && \
    apt-get -y update  && \
    apt-get -y install dotnet-sdk-3.1

RUN dotnet tool install -g dotnet-sos

ENV PATH="/root/.dotnet/tools:/usr/lib/llvm-8/bin:${PATH}"

RUN dotnet-sos install

RUN apt-get -y install build-essential

RUN dotnet tool install --global dotnet-ildasm --version 0.12.2
