FROM ubuntu:16.04

# https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/master/src/ubuntu/16.04/Dockerfile

# Install the base toolchain we need to build anything (clang, cmake, make and the like)
# this does not include libraries that we need to compile different projects, we'd like
# them in a different layer.
RUN apt-get update && \
    apt-get install -y apt-transport-https ca-certificates gnupg software-properties-common wget && \
    echo "deb http://llvm.org/apt/xenial/ llvm-toolchain-xenial-9 main" | tee -a /etc/apt/sources.list.d/llvm.list && \
    wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | apt-key add - && \
    wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc | apt-key add - && \
    apt-add-repository 'deb https://apt.kitware.com/ubuntu/ xenial main' && \
    apt-get update && \
    apt-get install -y \
            clang-9 \
            cmake \
            gdb \
            liblldb-6.0-dev \
            lldb-6.0 \
            llvm-9 \
            locales \
            make \
            python-lldb-6.0 \
            sudo && \
    apt-get clean

# Install tools used by the VSO build automation.
RUN apt-get install -y git \
            nodejs \
            npm \
            tar \
            zip && \
    apt-get clean && \
    npm install -g azure-cli@0.9.20 && \
    npm cache clean

# .NET SDK MSBuild requires US.UTF-8 locale to execute tasks
RUN locale-gen en_US.UTF-8

# Dependencies for CoreCLR, Mono and CoreFX
RUN apt-get install -y \
            autoconf \
            automake \
            build-essential \
            gettext \
            libcurl4-openssl-dev \
            libgdiplus \
            libicu-dev \
            libkrb5-dev \
            liblttng-ust-dev \
            libnuma-dev \
            libssl-dev \
            libtool \
            libunwind8-dev \
            libunwind8 \
            python3 \
            uuid-dev \
    && apt-get clean

RUN apt-get update && apt-get install -y clang-3.9


WORKDIR /app

RUN apt-get install locales
RUN locale-gen en_US.UTF-8

RUN git clone https://github.com/dotnet/diagnostics.git
RUN git clone https://github.com/dotnet/symstore.git
RUN git clone https://github.com/dotnet/sdk.git
RUN git clone https://github.com/dotnet/roslyn-sdk.git
RUN git clone https://github.com/dotnet/core
RUN git clone https://github.com/dotnet/roslyn-tools
RUN git clone https://github.com/dotnet/source-build
RUN git clone https://github.com/dotnet/symreader-portable
RUN git clone https://github.com/dotnet/symreader
RUN git clone https://github.com/dotnet/sourcelink
RUN git clone https://github.com/dotnet/metadata-tools
RUN git clone https://github.com/dotnet/toolset
RUN git clone https://github.com/dotnet/llvm-project
RUN git clone https://github.com/dotnet/vscode-dotnet-runtime
RUN git clone https://github.com/dotnet/buildtools
RUN git clone https://github.com/dotnet/ILMerge
RUN git clone https://github.com/dotnet/corefx-tools
RUN git clone https://github.com/dotnet/standard
RUN git clone https://github.com/dotnet/roslyn

RUN git clone https://github.com/dotnet/coreclr.git
RUN git clone https://github.com/dotnet/corefx.git

RUN cd coreclr     && git checkout v3.1.3    && ./build.sh
RUN cd corefx      && git checkout v3.1.3    && ./build.sh --restore --build --publish --configuration Debug

RUN cd sdk         && git checkout v3.1.201  && ./build.sh --restore --build --publish --configuration Debug

RUN cd /app/sdk/.dotnet && ./dotnet-build.sh

RUN cd diagnostics && git checkout 3.1.57502 && ./build.sh

RUN apt-get update -y && apt-get install -y clang
RUN apt-get update -y && apt-get install -y curl

#RUN ./diagnostics/build.sh --configuration debug
#RUN ./symstore/build.sh --configuration debug
#RUN dotnet tool install -g dotnet-symbol
