FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get clean && apt-get update -y && apt-get upgrade -y

RUN apt-get -y install software-properties-common

RUN add-apt-repository -y ppa:ubuntu-toolchain-r/test

RUN apt-get update

RUN apt-get -y install gcc-4.8 g++-4.8
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
RUN apt-get -y install build-essential
RUN apt-get -y install libc6-dbg gdb valgrind
RUN apt-get -y install binutils-dev
RUN apt-get -y install strace
RUN apt-get -y install ltrace
RUN apt-get -y install vim-common
RUN apt-get -y install libbfd-dev
RUN apt-get -y install binutils-multiarch-dev
RUN apt-get -y install libcapstone-dev
RUN apt-get -y install bash-completion
