version: "3"

services:

  llvm:
    hostname: llvm
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-llvm
    working_dir: /work
    security_opt:
      - seccomp:unconfined
    privileged: true
    volumes:
      - ..:/work
    command: /work/tests/scripts/start-llvm-server
