version: "3"

services:

  gdb:
    hostname: gdb
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-gdb
    working_dir: /work
    security_opt:
      - seccomp:unconfined
    expose:
      - "9999"
    ports:
      - "9999:9999"
    volumes:
      - ..:/work
