matrix:
  allow_failures:
    - os: windows
  include:
    - os: linux
      dist: xenial
      sudo: false
      addons:
        apt:
          sources:
          - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-5.0 main'
            key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
          - git
          - ninja-build
          - cmake
          - llvm-5.0
          - clang-5.0
      env: MATRIX_EVAL="CC=clang-5.0 CXX=clang++-5.0"
    - os: linux
      dist: trusty
      sudo: required
      env: TIZEN=1
      addons:
        apt:
          sources:
          - sourceline: 'deb http://download.tizen.org/tools/latest-release/Ubuntu_14.04/ /'
    - os: osx
      osx_image: xcode9.4
    - os: windows

env:
  global:
  - RELEASE_BRANCH=master
  - RELEASE_REPO=Samsung/netcoredbg
  - secure: "Sv69ZIMwaM7w56TZvZw06wLsx2csTd++KcIvb5IYO2yGWtobS3xSPWkzScuyjNkZLDqLbDcglH9vDMg/XgHxHGbz78/UDwj/CT+/nURQK3XzshDqObE6YXiK4VvlMCbfPlDriPku4fa/maAbLPmsvLc+sbIe9wyIjjY3Svxi4eiZ7O4xBdyFz9JOWJMIcKejPxwBG9SoHwJrrC6ni6iB5xMdNMML+W2nKxyCHyQXhk5QnNUCSTuFGVltY1pl9ws3MG6LU5Va1fismGbiui4M9wX5k9lzekT58tjsUC3MDqbe3+VJUv3nlfPl+95Ndb7obsDZYjcSuQ0e/7EiuxoUHAJY5mBQYeCaY2XpgB3rI7RW1UGmnnRF2iSe9CjI33T8foe5Ww8FlTsFuJ0ngtSH90emPqzehkjryxnkw8dTHdNJm9XI6eHOxnkBPdkFkP5ECDTOCnaC08+d+r6Yfv7Hr4xv+ic0pwML3OYZiQgEyf+cIQuwo+/g0KaLPEGDaR7O8sXCCfk9t4SwiDw7EMwAmr1ub1sQ1RJl2UKoykzz6y59U1DyBgqwuBpKrgzL5UbfnN8kAchVlhPLri1os2xoNkN/uP6Pfk99L/GclJwDKKg4aTzWaaKCog5/oUa/K25hl2Tc3N44IMA3U+yN+/A6YS1PaG+u2EmPVEyhGrFg6X8="

branches:
  except:
    - latest

language: cpp

cache:
  directories:
    - $HOME/GBS-ROOT/local/cache

before_install:
  - |
      if [ ${TRAVIS_OS_NAME} = 'osx' ]; then
        brew update
        brew install ninja
      elif [ ${TRAVIS_OS_NAME} = 'linux' ] && [ ! -z "$TIZEN" ]; then
        sudo apt-get update && sudo apt-get install -y --allow-unauthenticated gbs rpm2cpio
      fi

script:
  - |
      eval "${MATRIX_EVAL}"
      if [ -z "$TIZEN" ]; then
        # Build and run tests
        mkdir build && cd build
        if [ ${TRAVIS_OS_NAME} = 'windows' ]; then
          powershell -Command "Set-ExecutionPolicy Unrestricted"
          cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=$PWD/../bin
          cmake --build . --config Release --target install
        else
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PWD/../bin
          ninja && ninja install
        fi
        cd ..
        export PATH=$PWD/.dotnet:$PATH
        dotnet build tests && dotnet test tests/runner
      else
        # Verify that Tizen build does not break
        cat <<EOF > $HOME/.gbs.conf
      [general]
      profile = profile.target-TM1.unified
      buildroot = ~/GBS-ROOT/
      [profile.target-TM1.unified]
      repos = repo.target.unified, repo.target.base
      [repo.target.unified]
      url=http://download.tizen.org/releases/milestone/tizen/unified/tizen-unified_20180528.1/repos/standard/packages/
      [repo.target.base]
      url=http://download.tizen.org/releases/milestone/tizen/base/tizen-base_20180518.1/repos/standard/packages/
      EOF
        gbs build -A armv7l
      fi

before_deploy:
  - |
      if [ "$TRAVIS_BRANCH" = "$RELEASE_BRANCH" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
        # Tag last commit as 'latest'.
        git config --local user.name "Travis"
        git config --local user.email "travis@travis-ci.org"

        git remote add release "https://${GITHUB_API_KEY}@github.com/${RELEASE_REPO}.git"

        git push -d release latest
        git tag -d latest
        git tag -a "latest" -m "[Autogenerated] This is the latest version pushed to the ${TRAVIS_BRANCH} branch."
        git push release --tags
        # Prepare files for deployment
        if [ -z "$TIZEN" ]; then
          mv bin netcoredbg
          if [ ${TRAVIS_OS_NAME} = 'windows' ]; then
            7z a netcoredbg-win64-${TRAVIS_BRANCH}.zip netcoredbg
          else
            tar cfz netcoredbg-${TRAVIS_OS_NAME}-${TRAVIS_BRANCH}.tar.gz ./netcoredbg/*
          fi
        else
          # Generate tar.gz from rpm for Tizen SDK
          RPMFILE=$(find ~/GBS-ROOT/local/repos/target_TM1.unified/armv7l/RPMS -type f -name 'netcoredbg-[0-9]*.rpm')
          if [ ! -f "$RPMFILE" ]; then travis_terminate; fi
          PKGNAME=`rpm -q --qf "%{n}" -p $RPMFILE`
          PKGVERSION=`rpm -q --qf "%{v}" -p $RPMFILE`
          PKGARCH=`rpm -q --qf "%{arch}" -p $RPMFILE`
          TARGZNAME=$PKGNAME-$PKGVERSION-$PKGARCH.tar.gz
          mkdir unpacked && cd unpacked
          rpm2cpio "$RPMFILE" | cpio -idmv
          touch ./home/owner/share/tmp/sdk_tools/$PKGNAME/version-$PKGVERSION
          tar cfz ../$TARGZNAME --owner=root --group=root -C ./home/owner/share/tmp/sdk_tools .
          cd ..
          cp "$RPMFILE" ./
        fi
      fi
deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file:
    - "*.tar.gz"
    - "*.rpm"
    - "*.zip"
  file_glob: true
  skip_cleanup: true
  overwrite: true
  on:
    repo: $RELEASE_REPO
    branch: $RELEASE_BRANCH
